#!/bin/sh

# Generated by project-generator
GIT_BRANCH=$(git symbolic-ref -q --short HEAD)
GIT_LONG_COMMIT=$(git rev-parse --verify HEAD)
GIT_SHORT_COMMIT=$(git rev-parse --verify --short=10 HEAD)

CONAN_USER=${CONAN_USER:-qcs}
CONAN_CHANNEL=${CONAN_CHANNEL:-${GIT_BRANCH}}
CONAN_REMOTE=${CONAN_REMOTE:-local}

conan upload -r $CONAN_REMOTE IVEx/${GIT_LONG_COMMIT}@${CONAN_USER}/${CONAN_CHANNEL}
