#!/bin/sh

# Generated by project-generator
GIT_BRANCH=$(git symbolic-ref -q --short HEAD)
GIT_LONG_COMMIT=$(git rev-parse --verify HEAD)
GIT_SHORT_COMMIT=$(git rev-parse --verify --short=10 HEAD)

CONAN_USER=${CONAN_USER:-qcs}
CONAN_PROFILE=${CONAN_PROFILE:-default}
CONAN_CHANNEL=${CONAN_CHANNEL:-${GIT_BRANCH}}

conan create --profile ${CONAN_PROFILE} ./conanfile.py ${CONAN_USER}/${CONAN_CHANNEL} --build=missing
